### ISSUE TITLE
[feature request, question] vi-like input

### ISSUE THREAD

**Issue by rieje** [CogentRedTester/mpv-user-input#4]
Hi, I've tried [mpv-rename](https://github.com/Kayizoku/mpv-rename) which is based on this [thread](https://github.com/CogentRedTester/mpv-user-input/issues/2). It works as advertised, however, imo anything involving long input without basic vi-like input is awkward (e.g. ESC to enter normal mode)--spamming left/right arrow keys (especially with faster key rate) is less than ideal.  

Also (not a feature request, but a question): is it possible to have cursor default to right before an extension like `.mkv` as opposed to beginning of filename? It would be fine to assume the cursor is right before the last `.` regex-wise. The code is [mpv-rename](https://github.com/Kayizoku/mpv-rename/blob/main/Rename.lua).

Much appreciated.

**Comment by CogentRedTester** [comment]
User-input uses the same set of keybinds as the inbuilt `console.lua` script. You can see these keybinds [here](https://mpv.io/manual/master/#keybindings). They should have what you need. I do not intend to add any new bindings to keep this script consistent with the official REPL it is based on.

As for the cursor position, I have created a new option that allows scripts using this API to set the cursor position, and I have created a pull request for `mpv-rename` to use that option. It is up to them if they wish to merge the changes into the master banch.
