### ISSUE TITLE
`shared_script_property_observe` is obsolete in MPV `v0.37.0`

### ISSUE THREAD

**Issue by gsbabil** [CogentRedTester/mpv-user-input#8]
Hi @CogentRedTester,

Thank you for your MPV scripts.

The recent release of MPV, `v0.37.0` to be precise, has made the `shared_script_property_observe` function obsolete, and according to [this conversation](https://github.com/mpv-player/mpv/pull/10755), the recommendation is to switch to `user-data`.

I'm not very fluent in MPV scripting with Lua. But considering how useful your scripts and the `mpv-user-input` API layer are, I think it would be great to have these upgraded to support MPV `v0.37.0`.

I'm more than happy to help where I can. Please have a look. Thanks a lot!

```
[user_input] stack traceback:
[user_input]    [C]: at 0x010bc4fe50
[user_input]    [C]: at 0x010bc4f590
[user_input] Lua error: /Users/bart/.config/mpv/scripts/user-input.lua:568: attempt to call field 'shared_script_property_observe' (a nil value)
```

**Comment by CogentRedTester** [comment]
This should be fixed in the latest commits.
